Repository lfglabs-dev/api.starknet.quest, pull requests merged in 2024-10, with the labels that each got.

#277 Ft next id generate
  src/endpoints/admin/balance/create_balance.rs
  src/endpoints/admin/contract/create_contract.rs
  src/endpoints/admin/custom/create_custom.rs
  src/endpoints/admin/custom_api/create_custom_api.rs
  src/endpoints/admin/discord/create_discord.rs
  src/endpoints/admin/domain/create_domain.rs
  src/endpoints/admin/nft_uri/create_uri.rs
  src/endpoints/admin/quest/create_quest.rs
  src/endpoints/admin/quest_boost/create_boost.rs
  src/endpoints/admin/quiz/create_question.rs
  src/endpoints/admin/quiz/create_quiz.rs
  src/endpoints/admin/twitter/create_twitter_fw.rs
  src/endpoints/admin/twitter/create_twitter_rw.rs
  src/main.rs
  src/models.rs
  src/utils.rs
Labels: ❌ Change request

#280 feat: Add GET Route /defi/rewards to Centralize DeFi Spring Reward Collection
  Cargo.toml
  config.template.toml
  src/config.rs
  src/endpoints/defi/mod.rs
  src/endpoints/defi/rewards.rs
  src/endpoints/get_boosted_quests.rs
  src/endpoints/get_completed_quests.rs
  src/endpoints/get_quest_participants.rs
  src/endpoints/get_trending_quests.rs
  src/endpoints/has_completed_quest.rs
  src/endpoints/leaderboard/get_ranking.rs
  src/endpoints/leaderboard/get_static_info.rs
  src/endpoints/mod.rs
  src/endpoints/quest_boost/get_claim_params.rs
  src/endpoints/quest_boost/get_completed_boosts.rs
  src/endpoints/quests/claimable.rs
  src/models.rs
  src/utils.rs
  tests/endpoints.rs
Labels: ❌ Change request

#285 fix: proscore task
  src/endpoints/quests/proscore/verify_signers.rs
Labels: 🔥 Ready for review

#286 fix: removing already claimed amount for nimbora
  src/endpoints/defi/rewards.rs
Labels: 🔥 Ready for review

#283 Integrate Nimbora API for accurate APR calculation
  src/endpoints/achievements/verify_seniority.rs
  src/endpoints/admin/balance/update_balance.rs
  src/endpoints/admin/contract/mod.rs
  src/endpoints/admin/contract/update_contract.rs
  src/endpoints/admin/custom/update_custom.rs
  src/endpoints/admin/custom_api/mod.rs
  src/endpoints/admin/custom_api/update_custom_api.rs
  src/endpoints/admin/delete_task.rs
  src/endpoints/admin/discord/update_discord.rs
  src/endpoints/admin/domain/update_domain.rs
  src/endpoints/admin/mod.rs
  src/endpoints/admin/nft_uri/get_nft_uri.rs
  src/endpoints/admin/nft_uri/update_uri.rs
  src/endpoints/admin/quest/get_quest.rs
  src/endpoints/admin/quest/get_quests.rs
  src/endpoints/admin/quest/get_tasks.rs
  src/endpoints/admin/quest/update_quest.rs
  src/endpoints/admin/quest_boost/update_boost.rs
  src/endpoints/admin/quiz/create_question.rs
  src/endpoints/admin/quiz/get_quiz.rs
  src/endpoints/admin/quiz/update_question.rs
  src/endpoints/admin/quiz/update_quiz.rs
  src/endpoints/admin/twitter/create_twitter_fw.rs
  src/endpoints/admin/twitter/update_twitter_fw.rs
  src/endpoints/admin/twitter/update_twitter_rw.rs
  src/endpoints/admin/user/create_user.rs
  src/endpoints/discover/defi/get_alt_protocol_stats.rs
  src/endpoints/mod.rs
  src/endpoints/quests/discord_fw_callback.rs
  src/endpoints/quests/mod.rs
  src/endpoints/quests/verify_balance.rs
  src/endpoints/quests/verify_contract.rs
  src/endpoints/quests/verify_custom_api.rs
  src/middleware/auth.rs
  src/middleware/mod.rs
Labels: ❌ Change request

#289 fix: defi alt protocols apr
  src/endpoints/discover/defi/get_alt_protocol_stats.rs
Labels: 🔥 Ready for review

#282 feat: improve custom api error message
  src/endpoints/quests/verify_custom_api.rs
Labels: 🔥 Ready for review

#294 fix: nimbora rewards
  src/endpoints/defi/rewards.rs
  src/models.rs
Labels: 🚨 Important bug, 🔥 Ready for review

#309 Feat: Add Vesu for DeFiSpring rewards
  config.template.toml
  src/config.rs
  src/endpoints/defi/rewards.rs
  src/models.rs
Labels: ❌ Change request

#310 fix: hiding vesu when 0 rewards
  src/endpoints/defi/rewards.rs
Labels: 🔥 Ready for review
